### ISSUE TITLE
Failed to get data from environment variable - Error

### ISSUE THREAD

**Issue by archit-khanna** [CheckPointSW/charts#58]
Hello, 

I recently followed the deployment process to add dome9 cloudguard to my Azure Kubernetes Cluster but ran into an issue that is causing the deployment to fail. 

![image](https://user-images.githubusercontent.com/76162573/122198013-a98af200-ce90-11eb-9197-8343c6b0e785.png)

The command I used for the helm deployment is:

`helm install asset-mgmt cloudguard --repo https://raw.githubusercontent.com/CheckPointSW/charts/master/repository/ 
--set credentials.user=00000-00000-00000-00000 
--set credentials.secret=00000-00000-00000-00000 
--set clusterID=undefined --set addons.imageScan.enabled=true 
--set addons.admissionControl.enabled=true 
--namespace dome9 --create-namespace`

And when I look at the pods and logs I get the following: 

![image](https://user-images.githubusercontent.com/76162573/122198532-24540d00-ce91-11eb-94cc-e00dee02da35.png)

![image](https://user-images.githubusercontent.com/76162573/122198595-346bec80-ce91-11eb-9fd3-8128aa16e0c1.png)

![image](https://user-images.githubusercontent.com/76162573/122198681-4483cc00-ce91-11eb-885a-950318330f93.png)

![image](https://user-images.githubusercontent.com/76162573/122198753-56fe0580-ce91-11eb-90b7-23630d286adb.png)

Can I get some help with the deployment and if I am doing it right?

**Comment by chkp-yonatanph** [comment]
Hi,

I notice that the clusterid is 'undefined', which is probably the reason for the failure. 
This is the first time I've seen this behavior. 
I'm not sure if this is a BE or GUI issue either. 
Can you please send me an email at yonatanph@checkpoint.com with some additional information?
What browser are you using? What is your account ID and datacenter? (you can find that in settings->account info page)

**Comment by archit-khanna** [comment]
Hi @chkp-yonatanph I'll do that right away, thank you!

**Comment by chkp-yonatanph** [comment]
This issue was (partially) related to containerd. 
We no longer need users to manually set the runtime environment as we now have automatic detection for containerd.
