### ISSUE TITLE
runAsUser option unavailable

### ISSUE THREAD

**Issue by stevenwarrenfis** [CheckPointSW/charts#81]
Is it possible to have a runAsUser for all of the securityContexts or is this not possible due to the access that this helm deployment requires? Ideally I would like to have all deployments within my cluster to run as a non-root user and for me to be able to specify the securityContext.runAsUser element.

**Comment by chkp-rigor** [comment]
Hi @stevenwarrenfis,
Some our containers should run as root due to the required functionality. All the rest run as non-root user with id and group id above 10000 to prevent overlapping with a system user.
Regards,
Igor

**Comment by stevenwarrenfis** [comment]
Gotcha, thank you for the info!
