### ISSUE TITLE
Agent Connectivity Requirements

### ISSUE THREAD

**Issue by KevalFIS** [CheckPointSW/charts#88]
Runtime Protection agents need connectivity to http://mirrors.edge.kernel.org/ for downloading kernel packages. NGFW intercept the package being downloaded and fail the download if vulnerable packages are identified. Can this be switched to a secure URL so NGFW is not able to knock down the download of required kernel package? Below outputs using both http and https URL.

$ wget http://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.14.238.tar.gz
Connecting to mirrors.edge.kernel.org (139.178.84.19:80)
saving to 'linux-4.14.238.tar.gz'
linux-4.14.238.tar.g 69% |************************************************************************************* | 103M 0:00:12 ETAwget: read error: Connection reset by peer

$ wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.14.238.tar.gz
Connecting to mirrors.edge.kernel.org (139.178.84.19:443)
saving to 'linux-4.14.238.tar.gz'
linux-4.14.238.tar.g 100% |****************************************************************************************************************************| 149M 0:00:00 ETA
'linux-4.14.238.tar.gz' saved

**Comment by Dor-Cohen** [comment]
Thanks Keval,

To install kernel headers the following command needs to be executed on each node prior to deployment: 
  
Ubuntu/Debian:
apt-get install -y linux-headers-$(uname -r) 
  
CentOS/RHEL/Amazon Linux:
yum -y install kernel-devel-$(uname -r) 
  
Google COS/Bottlerocket/RHCOS(OpenShift):
Not required

We are working on a long-term solution and will update.

**Comment by chkp-alexgl** [comment]
Hi @KevalFIS,

Recent versions of the Helm chart do not attempt downloading 'vanilla' kernel sources from the above URL, and rely on `kernel-devel` (or equivalent) package on the nodes instead. On some platforms, the package needs to be installed prior to deployment of the runtime agent (as outlined in the docs [1]). We are working on increasing the coverage of platforms where this happens automatically as part of our agent deployment. If your platform is still not supported, please, let us know, and follow the instructions above to install them prior to deployment of runtime agents (e.g., as part of the automation that provisions the nodes).

[1] https://sc1.checkpoint.com/documents/CloudGuard_Dome9/Documentation/Workload-Protection/Kubernetes-Containers/Kubernetes-Runtime-Protection.htm
